

from dotenv import load_dotenv
import os



 
DEBUG = False
TESTING = False
SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")
SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
API_KEY="2b101mmdc8gSRboBNm5ERTupXe"